// Code generated by port-monolith-go: orders's view of payments-service (github.com/acme/shop/internal/payments).
// Only the CW-SEAM stubs need an edit; the declarations mirror the provider's API.
package payments

// Gateway is orders's copy of payments-service's contract.
type Gateway struct {
}
