// Code generated by port-monolith-go: orders's view of inventory-service (github.com/acme/shop/internal/inventory).
// Only the CW-SEAM stubs need an edit; the declarations mirror the provider's API.
package inventory

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"

	"github.com/acme/shop/pkg/httpx"
	"gorm.io/gorm"
)

func baseURL() string {
	if v := os.Getenv("INVENTORY_SERVICE_URL"); v != "" {
		return v
	}
	return "http://inventory-service:8080"
}

// remoteError is the error the in-process call returned, as inventory-service
// answered it: the message in its JSON body ({"error": …}, or a problem's
// detail/title), unwrapped, so a caller shows exactly what the monolith showed.
// Use it for every answer of 400 or above, 404 included.
func remoteError(resp *http.Response) error {
	body, _ := io.ReadAll(io.LimitReader(resp.Body, 64<<10))
	var e struct {
		Error  string `json:"error"`
		Detail string `json:"detail"`
		Title  string `json:"title"`
	}
	if json.Unmarshal(body, &e) == nil {
		for _, m := range []string{e.Error, e.Detail, e.Title} {
			if m != "" {
				return errors.New(m)
			}
		}
	}
	return fmt.Errorf("inventory-service: status %d", resp.StatusCode)
}

// Service is inventory-service's Service, seen from orders: every method is a remote call.
type Service struct {
	baseURL string
	client  *http.Client
}

func newService() *Service {
	return &Service{baseURL: baseURL(), client: httpx.NewClient()}
}

// Reserve posts to inventory-service's POST /v1/inventory/reserve. The remote
// service owns the stock rows, so the caller's tx is not used. Reserving is not
// idempotent, so the call is never retried.
func (c *Service) Reserve(tx *gorm.DB, productID uint, qty int) (bool, error) {
	payload, err := json.Marshal(map[string]any{"product_id": productID, "qty": qty})
	if err != nil {
		return false, err
	}
	req, err := http.NewRequestWithContext(context.Background(), http.MethodPost, c.baseURL+"/v1/inventory/reserve", bytes.NewReader(payload))
	if err != nil {
		return false, err
	}
	req.Header.Set("Content-Type", "application/json")
	resp, err := c.client.Do(req)
	if err != nil {
		return false, err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		return false, remoteError(resp)
	}
	var out struct {
		Reserved bool `json:"reserved"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&out); err != nil {
		return false, err
	}
	return out.Reserved, nil
}

func NewService(db *gorm.DB) *Service {
	return newService()
}
