// Code generated by port-monolith-go: orders's view of inventory-service (github.com/acme/shop/internal/inventory).
// Only the CW-SEAM stubs need an edit; the declarations mirror the provider's API.
package inventory

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"os"

	"github.com/acme/shop/pkg/httpx"
	"gorm.io/gorm"
)

func baseURL() string {
	if v := os.Getenv("INVENTORY_SERVICE_URL"); v != "" {
		return v
	}
	return "http://inventory-service:8080"
}

// ErrNotFound is returned when inventory-service has no stock item for the given product.
var ErrNotFound = errors.New("inventory: stock item not found")

type reserveRequest struct {
	ProductID uint `json:"product_id"`
	Quantity  int  `json:"quantity"`
}

type reserveResponse struct {
	Reserved bool `json:"reserved"`
}

// Service is inventory-service's Service, seen from orders: every method is a remote call.
type Service struct {
	baseURL string
	client  *http.Client
}

func newService() *Service {
	return &Service{baseURL: baseURL(), client: httpx.NewClient()}
}

// Reserve calls inventory-service's POST /v1/stockitem/reserve. tx is kept in
// the signature to mirror the provider's API, but the write now happens
// remotely: it is no longer part of this transaction.
func (c *Service) Reserve(tx *gorm.DB, productID uint, qty int) (bool, error) {
	body, err := json.Marshal(reserveRequest{ProductID: productID, Quantity: qty})
	if err != nil {
		return false, err
	}
	req, err := http.NewRequestWithContext(context.Background(), http.MethodPost, c.baseURL+"/v1/stockitem/reserve", bytes.NewReader(body))
	if err != nil {
		return false, err
	}
	req.Header.Set("Content-Type", "application/json")
	resp, err := c.client.Do(req)
	if err != nil {
		return false, fmt.Errorf("inventory: reserve stock: %w", err)
	}
	defer resp.Body.Close()
	switch resp.StatusCode {
	case http.StatusOK:
		var out reserveResponse
		if err := json.NewDecoder(resp.Body).Decode(&out); err != nil {
			return false, fmt.Errorf("inventory: decode reserve response: %w", err)
		}
		return out.Reserved, nil
	case http.StatusConflict:
		return false, nil
	case http.StatusNotFound:
		return false, ErrNotFound
	default:
		return false, fmt.Errorf("inventory: reserve stock: unexpected status %d", resp.StatusCode)
	}
}

func NewService(db *gorm.DB) *Service {
	return newService()
}
