// Code generated by port-monolith-go — the tables the service map assigned to orders.
package app

import (
	"github.com/acme/shop/services/orders/internal/orders"
)

// models lists the persisted types THIS service owns; New migrates exactly these.
func models() []any {
	return []any{
		&orders.Order{},
		&orders.OrderLine{},
	}
}
