// Code generated by port-monolith-go from cmd/shop/main.go — the monolith's own wiring,
// narrowed to the orders-service. An edit here is kept on the next port.
package app

import (
	"os"

	"github.com/acme/shop/pkg/httpx"
	"github.com/acme/shop/services/orders/internal/clients/catalog"
	"github.com/acme/shop/services/orders/internal/clients/customers"
	"github.com/acme/shop/services/orders/internal/clients/inventory"
	"github.com/acme/shop/services/orders/internal/clients/payments"
	"github.com/acme/shop/services/orders/internal/orders"
	"github.com/acme/shop/services/orders/internal/platform"
	"github.com/gin-gonic/gin"
)

// wire constructs the orders-service's domain services and mounts its routes.
func wire(r *gin.Engine, d *Deps) error {
	db := d.DB
	bus := platform.NewBus()
	catalogSvc := catalog.NewService(db)
	customerSvc := customers.NewService(db)
	inventorySvc := inventory.NewService(db)
	paymentSvc := payments.NewService(db, payments.NewGateway(os.Getenv("PAYMENTS_URL")))
	orderSvc := orders.NewService(db, catalogSvc, customerSvc, inventorySvc, paymentSvc, bus)
	auth := platform.AuthMiddleware()
	// A call from another service of this platform (pkg/httpx internal.go) skips the
	// monolith's user check, as the in-process call it replaces did.
	r.Use(func(c *gin.Context) {
		if httpx.IsInternal(c.Request) {
			c.Next()
			return
		}
		auth(c)
	})
	api := r.Group("/api")
	orders.RegisterRoutes(api, orderSvc)
	return nil
}
