// Code generated by port-monolith-go: orders's view of payments-service (github.com/acme/shop/internal/payments).
// Only the CW-SEAM stubs need an edit; the declarations mirror the provider's API.
package payments

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"os"

	"github.com/acme/shop/pkg/httpx"
	contract "github.com/acme/shop/services/orders/internal/contracts/payments"
	"gorm.io/gorm"
)

func baseURL() string {
	if v := os.Getenv("PAYMENTS_SERVICE_URL"); v != "" {
		return v
	}
	return "http://payments-service:8080"
}

// The provider's contract types and constants, as orders holds them.
type Gateway = contract.Gateway

type chargeRequest struct {
	OrderID uint    `json:"order_id"`
	Amount  float64 `json:"amount"`
}

// Service is payments-service's Service, seen from orders: every method is a remote call.
type Service struct {
	baseURL string
	client  *http.Client
}

func newService() *Service {
	return &Service{baseURL: baseURL(), client: httpx.NewClient()}
}

// Charge calls payments-service's POST /v1/payment/charge. tx is kept in the
// signature to mirror the provider's API, but the charge now happens
// remotely: it is no longer part of this transaction.
func (c *Service) Charge(tx *gorm.DB, orderID uint, amount float64) error {
	body, err := json.Marshal(chargeRequest{OrderID: orderID, Amount: amount})
	if err != nil {
		return err
	}
	req, err := http.NewRequestWithContext(context.Background(), http.MethodPost, c.baseURL+"/v1/payment/charge", bytes.NewReader(body))
	if err != nil {
		return err
	}
	req.Header.Set("Content-Type", "application/json")
	resp, err := c.client.Do(req)
	if err != nil {
		return fmt.Errorf("payments: charge: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK && resp.StatusCode != http.StatusCreated {
		return fmt.Errorf("payments: charge: unexpected status %d", resp.StatusCode)
	}
	return nil
}

func NewService(db *gorm.DB, gw *Gateway) *Service {
	return newService()
}

func NewGateway(baseURL string) *Gateway {
	return &Gateway{}
}
