// Code generated by port-monolith-go — the tables the service map assigned to catalog.
package app

import (
	"github.com/acme/shop/services/catalog/internal/catalog"
)

// models lists the persisted types THIS service owns; New migrates exactly these.
func models() []any {
	return []any{
		&catalog.Category{},
		&catalog.Product{},
	}
}
