// Code generated by port-monolith-go from cmd/shop/main.go — the monolith's own wiring,
// narrowed to the catalog-service. An edit here is kept on the next port.
package app

import (
	"github.com/acme/shop/services/catalog/internal/catalog"
	"github.com/acme/shop/services/catalog/internal/platform"
	"github.com/gin-gonic/gin"
)

// wire constructs the catalog-service's domain services and mounts its routes.
func wire(r *gin.Engine, d *Deps) error {
	db := d.DB
	catalogSvc := catalog.NewService(db)
	r.Use(platform.AuthMiddleware())
	api := r.Group("/api")
	catalog.RegisterRoutes(api, catalogSvc)
	return nil
}
