// Code generated by port-monolith-go: orders's view of catalog-service (github.com/acme/shop/internal/catalog).
// Only the CW-SEAM stubs need an edit; the declarations mirror the provider's API.
package catalog

// Product is orders's copy of catalog-service's contract.
type Product struct {
	ID         uint     `gorm:"primaryKey" json:"id"`
	SKU        string   `gorm:"uniqueIndex;size:40" json:"sku" binding:"required"`
	Name       string   `gorm:"size:200" json:"name" binding:"required"`
	Price      float64  `json:"price" binding:"required,gt=0"`
	CategoryID uint     `json:"categoryId"`
	Category   Category `gorm:"foreignKey:CategoryID" json:"-"`
}

// Category is orders's copy of catalog-service's contract.
type Category struct {
	ID       uint      `gorm:"primaryKey" json:"id"`
	Name     string    `gorm:"size:120;not null" json:"name"`
	Products []Product `json:"products,omitempty"`
}
