// Code generated by port-monolith-go: orders's view of catalog-service (github.com/acme/shop/internal/catalog).
// Only the CW-SEAM stubs need an edit; the declarations mirror the provider's API.
//
// catalog-service also serves the monolith's own routes, at exactly these paths
// (prefix included); each method below has its own route, named in its body:
//
//	GET /api/products
//	POST /api/products
package catalog

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"time"

	"github.com/acme/shop/pkg/httpx"
	contract "github.com/acme/shop/services/orders/internal/contracts/catalog"
	"gorm.io/gorm"
)

func baseURL() string {
	if v := os.Getenv("CATALOG_SERVICE_URL"); v != "" {
		return v
	}
	return "http://catalog-service:8080"
}

// remoteError is the error the in-process call returned, as catalog-service
// answered it: the message in its JSON body ({"error": …}, or a problem's
// detail/title), unwrapped, so a caller shows exactly what the monolith showed.
// Use it for every answer of 400 or above, 404 included.
func remoteError(resp *http.Response) error {
	body, _ := io.ReadAll(io.LimitReader(resp.Body, 64<<10))
	var e struct {
		Error  string `json:"error"`
		Detail string `json:"detail"`
		Title  string `json:"title"`
	}
	if json.Unmarshal(body, &e) == nil {
		for _, m := range []string{e.Error, e.Detail, e.Title} {
			if m != "" {
				return errors.New(m)
			}
		}
	}
	return fmt.Errorf("catalog-service: status %d", resp.StatusCode)
}

// The provider's contract types and constants, as orders holds them.
type Product = contract.Product
type Category = contract.Category

// Service is catalog-service's Service, seen from orders: every method is a remote call.
type Service struct {
	baseURL string
	client  *http.Client
}

func newService() *Service {
	return &Service{baseURL: baseURL(), client: httpx.NewClient()}
}

const (
	maxAttempts = 3
	baseBackoff = 100 * time.Millisecond
)

// post sends body as JSON to path and decodes a 2xx answer into out. Transport
// errors and 5xx answers are retried with exponential backoff only when retry
// is set (the call is safe to repeat); any answer of 400 or above otherwise
// becomes remoteError.
func (c *Service) post(path string, body, out any, retry bool) error {
	payload, err := json.Marshal(body)
	if err != nil {
		return err
	}
	attempts := 1
	if retry {
		attempts = maxAttempts
	}
	var lastErr error
	for i := 0; i < attempts; i++ {
		if i > 0 {
			time.Sleep(baseBackoff << (i - 1))
		}
		req, err := http.NewRequestWithContext(context.Background(), http.MethodPost, c.baseURL+path, bytes.NewReader(payload))
		if err != nil {
			return err
		}
		req.Header.Set("Content-Type", "application/json")
		resp, err := c.client.Do(req)
		if err != nil {
			lastErr = err
			continue
		}
		if resp.StatusCode >= 500 {
			lastErr = remoteError(resp)
			resp.Body.Close()
			continue
		}
		defer resp.Body.Close()
		if resp.StatusCode >= 400 {
			return remoteError(resp)
		}
		return json.NewDecoder(resp.Body).Decode(out)
	}
	return lastErr
}

// Create posts to catalog-service's POST /api/products and copies the stored
// product (with its assigned id) back into p.
func (c *Service) Create(p *Product) error {
	return c.post("/api/products", p, p, false)
}

// PriceOf asks catalog-service's POST /v1/catalog/price_of for a product's price.
func (c *Service) PriceOf(productID uint) (float64, error) {
	var out struct {
		Price float64 `json:"price"`
	}
	if err := c.post("/v1/catalog/price_of", map[string]uint{"productId": productID}, &out, true); err != nil {
		return 0, err
	}
	return out.Price, nil
}

func NewService(db *gorm.DB) *Service {
	return newService()
}
