// Code generated by port-monolith-go: orders's view of catalog-service (github.com/acme/shop/internal/catalog).
// Only the CW-SEAM stubs need an edit; the declarations mirror the provider's API.
package catalog

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"os"
	"time"

	"github.com/acme/shop/pkg/httpx"
	contract "github.com/acme/shop/services/orders/internal/contracts/catalog"
	"gorm.io/gorm"
)

func baseURL() string {
	if v := os.Getenv("CATALOG_SERVICE_URL"); v != "" {
		return v
	}
	return "http://catalog-service:8080"
}

// ErrNotFound is returned when catalog-service has no product for the given id.
var ErrNotFound = errors.New("catalog: product not found")

// The provider's contract types and constants, as orders holds them.
type Product = contract.Product
type Category = contract.Category

// Service is catalog-service's Service, seen from orders: every method is a remote call.
type Service struct {
	baseURL string
	client  *http.Client
}

func newService() *Service {
	return &Service{baseURL: baseURL(), client: httpx.NewClient()}
}

func (c *Service) Create(p *Product) error {
	body, err := json.Marshal(p)
	if err != nil {
		return err
	}
	req, err := http.NewRequestWithContext(context.Background(), http.MethodPost, c.baseURL+"/api/products", bytes.NewReader(body))
	if err != nil {
		return err
	}
	req.Header.Set("Content-Type", "application/json")
	resp, err := c.client.Do(req)
	if err != nil {
		return fmt.Errorf("catalog: create product: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusCreated && resp.StatusCode != http.StatusOK {
		return fmt.Errorf("catalog: create product: unexpected status %d", resp.StatusCode)
	}
	var created Product
	if err := json.NewDecoder(resp.Body).Decode(&created); err != nil {
		return fmt.Errorf("catalog: decode create product response: %w", err)
	}
	*p = created
	return nil
}

func (c *Service) PriceOf(productID uint) (float64, error) {
	var resp *http.Response
	var err error
	const maxAttempts = 3
	for attempt := 0; attempt < maxAttempts; attempt++ {
		var req *http.Request
		req, err = http.NewRequestWithContext(context.Background(), http.MethodGet, c.baseURL+"/api/products", nil)
		if err != nil {
			return 0, err
		}
		resp, err = c.client.Do(req)
		if err != nil {
			if attempt < maxAttempts-1 {
				time.Sleep(backoff(attempt))
				continue
			}
			return 0, fmt.Errorf("catalog: list products: %w", err)
		}
		if resp.StatusCode >= http.StatusInternalServerError {
			resp.Body.Close()
			if attempt < maxAttempts-1 {
				time.Sleep(backoff(attempt))
				continue
			}
			return 0, fmt.Errorf("catalog: list products: unexpected status %d", resp.StatusCode)
		}
		break
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return 0, fmt.Errorf("catalog: list products: unexpected status %d", resp.StatusCode)
	}
	var products []Product
	if err := json.NewDecoder(resp.Body).Decode(&products); err != nil {
		return 0, fmt.Errorf("catalog: decode products response: %w", err)
	}
	for _, p := range products {
		if p.ID == productID {
			return p.Price, nil
		}
	}
	return 0, ErrNotFound
}

func backoff(attempt int) time.Duration {
	return time.Duration(1<<attempt) * 100 * time.Millisecond
}

func NewService(db *gorm.DB) *Service {
	return newService()
}
