// Code generated by port-monolith-go: inventory's view of orders-service (github.com/acme/shop/internal/orders).
// Only the CW-SEAM stubs need an edit; the declarations mirror the provider's API.
//
// orders-service also serves the monolith's own routes, at exactly these paths
// (prefix included); each method below has its own route, named in its body:
//
//	GET /api/orders/mine
//	POST /api/orders
package orders

const TopicOrderPlaced = "order.placed"
