// Code generated by port-monolith-go: inventory's view of orders-service (github.com/acme/shop/internal/orders).
// Only the CW-SEAM stubs need an edit; the declarations mirror the provider's API.
package orders

const TopicOrderPlaced = "order.placed"
