// Code generated by port-monolith-go — the tables the service map assigned to customers.
package app

import (
	"github.com/acme/shop/services/customers/internal/customers"
)

// models lists the persisted types THIS service owns; New migrates exactly these.
func models() []any {
	return []any{
		&customers.Customer{},
	}
}
