// Code generated by port-monolith-go from cmd/shop/main.go — the monolith's own wiring,
// narrowed to the customers-service. An edit here is kept on the next port.
package app

import (
	"github.com/acme/shop/pkg/httpx"
	"github.com/acme/shop/services/customers/internal/customers"
	"github.com/acme/shop/services/customers/internal/platform"
	"github.com/gin-gonic/gin"
)

// wire constructs the customers-service's domain services and mounts its routes.
func wire(r *gin.Engine, d *Deps) error {
	db := d.DB
	customerSvc := customers.NewService(db)
	auth := platform.AuthMiddleware()
	// A call from another service of this platform (pkg/httpx internal.go) skips the
	// monolith's user check, as the in-process call it replaces did.
	r.Use(func(c *gin.Context) {
		if httpx.IsInternal(c.Request) {
			c.Next()
			return
		}
		auth(c)
	})
	api := r.Group("/api")
	customers.RegisterRoutes(api, customerSvc)
	return nil
}
