// Code generated by port-monolith-go from cmd/shop/main.go — the monolith's own wiring,
// narrowed to the customers-service. An edit here is kept on the next port.
package app

import (
	"github.com/acme/shop/services/customers/internal/customers"
	"github.com/acme/shop/services/customers/internal/platform"
	"github.com/gin-gonic/gin"
)

// wire constructs the customers-service's domain services and mounts its routes.
func wire(r *gin.Engine, d *Deps) error {
	db := d.DB
	customerSvc := customers.NewService(db)
	r.Use(platform.AuthMiddleware())
	api := r.Group("/api")
	customers.RegisterRoutes(api, customerSvc)
	return nil
}
