// Code generated by port-monolith-go — the tables the service map assigned to inventory.
package app

import (
	"github.com/acme/shop/services/inventory/internal/inventory"
)

// models lists the persisted types THIS service owns; New migrates exactly these.
func models() []any {
	return []any{
		&inventory.StockItem{},
	}
}
