// Code generated by port-monolith-go from cmd/shop/main.go — the monolith's own wiring,
// narrowed to the inventory-service. An edit here is kept on the next port.
package app

import (
	"context"
	"time"

	pkgevents "github.com/acme/shop/pkg/events"
	"github.com/acme/shop/services/inventory/internal/events"
	"github.com/acme/shop/services/inventory/internal/httpapi"
	"github.com/acme/shop/services/inventory/internal/inventory"
	"github.com/acme/shop/services/inventory/internal/jobs"
	"github.com/acme/shop/services/inventory/internal/platform"
	"github.com/gin-gonic/gin"
)

// wire constructs the inventory-service's domain services and mounts its routes.
func wire(r *gin.Engine, d *Deps) error {
	db := d.DB
	inventorySvc := inventory.NewService(db)
	if d.Bus != nil && d.SQL != nil {
		seen := pkgevents.SQLSeen{DB: d.SQL}
		if err := events.SubscribeOrderPlaced(context.Background(), d.Bus, seen, inventorySvc); err != nil {
			return err
		}
	}
	if d.SQL != nil {
		jobs.Run(context.Background(), d.SQL, time.Minute, inventorySvc.Restock)
	}
	r.Use(platform.AuthMiddleware())
	httpapi.RegisterRoutes(r, db, inventorySvc)
	return nil
}
