// Code generated by port-monolith-go from cmd/shop/main.go — the monolith's own wiring,
// narrowed to the inventory-service. An edit here is kept on the next port.
package app

import (
	"context"
	"os"
	"os/signal"
	"syscall"
	"time"

	pkgevents "github.com/acme/shop/pkg/events"
	"github.com/acme/shop/pkg/httpx"
	"github.com/acme/shop/services/inventory/internal/events"
	"github.com/acme/shop/services/inventory/internal/httpapi"
	"github.com/acme/shop/services/inventory/internal/inventory"
	"github.com/acme/shop/services/inventory/internal/jobs"
	"github.com/acme/shop/services/inventory/internal/platform"
	"github.com/gin-gonic/gin"
)

// wire constructs the inventory-service's domain services and mounts its routes.
func wire(r *gin.Engine, d *Deps) error {
	db := d.DB
	inventorySvc := inventory.NewService(db)
	// Background work stops on SIGTERM/interrupt.
	ctx, _ := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	if d.Bus != nil && d.SQL != nil {
		seen := pkgevents.SQLSeen{DB: d.SQL}
		if err := events.SubscribeOrderPlaced(ctx, d.Bus, seen, inventorySvc); err != nil {
			return err
		}
	}
	if d.SQL != nil {
		go jobs.Run(ctx, d.SQL, time.Minute, inventorySvc.Restock)
	}
	auth := platform.AuthMiddleware()
	// A call from another service of this platform (pkg/httpx internal.go) skips the
	// monolith's user check, as the in-process call it replaces did.
	r.Use(func(c *gin.Context) {
		if httpx.IsInternal(c.Request) {
			c.Next()
			return
		}
		auth(c)
	})
	httpapi.RegisterRoutes(r, db, inventorySvc)
	return nil
}
