// Code generated by port-monolith-go: orders's view of customers-service (github.com/acme/shop/internal/customers).
// Only the CW-SEAM stubs need an edit; the declarations mirror the provider's API.
package customers

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"os"
	"strconv"
	"time"

	"github.com/acme/shop/pkg/httpx"
	"gorm.io/gorm"
)

func baseURL() string {
	if v := os.Getenv("CUSTOMERS_SERVICE_URL"); v != "" {
		return v
	}
	return "http://customers-service:8080"
}

// ErrNotFound is returned when customers-service has no customer for the given id.
var ErrNotFound = errors.New("customers: customer not found")

// customerView is the subset of customers-service's Customer that IsActive needs.
type customerView struct {
	Active bool `json:"active"`
}

// Service is customers-service's Service, seen from orders: every method is a remote call.
type Service struct {
	baseURL string
	client  *http.Client
}

func newService() *Service {
	return &Service{baseURL: baseURL(), client: httpx.NewClient()}
}

func (c *Service) IsActive(id uint) (bool, error) {
	var resp *http.Response
	var err error
	const maxAttempts = 3
	url := c.baseURL + "/api/customers/" + strconv.FormatUint(uint64(id), 10)
	for attempt := 0; attempt < maxAttempts; attempt++ {
		var req *http.Request
		req, err = http.NewRequestWithContext(context.Background(), http.MethodGet, url, nil)
		if err != nil {
			return false, err
		}
		resp, err = c.client.Do(req)
		if err != nil {
			if attempt < maxAttempts-1 {
				time.Sleep(backoff(attempt))
				continue
			}
			return false, fmt.Errorf("customers: get customer: %w", err)
		}
		if resp.StatusCode >= http.StatusInternalServerError {
			resp.Body.Close()
			if attempt < maxAttempts-1 {
				time.Sleep(backoff(attempt))
				continue
			}
			return false, fmt.Errorf("customers: get customer: unexpected status %d", resp.StatusCode)
		}
		break
	}
	defer resp.Body.Close()
	if resp.StatusCode == http.StatusNotFound {
		return false, ErrNotFound
	}
	if resp.StatusCode != http.StatusOK {
		return false, fmt.Errorf("customers: get customer: unexpected status %d", resp.StatusCode)
	}
	var view customerView
	if err := json.NewDecoder(resp.Body).Decode(&view); err != nil {
		return false, fmt.Errorf("customers: decode customer response: %w", err)
	}
	return view.Active, nil
}

func backoff(attempt int) time.Duration {
	return time.Duration(1<<attempt) * 100 * time.Millisecond
}

func NewService(db *gorm.DB) *Service {
	return newService()
}
