// Code generated by port-monolith-go: orders's view of customers-service (github.com/acme/shop/internal/customers).
// Only the CW-SEAM stubs need an edit; the declarations mirror the provider's API.
//
// customers-service also serves the monolith's own routes, at exactly these paths
// (prefix included); each method below has its own route, named in its body:
//
//	GET /api/customers/:id
//	POST /api/customers
package customers

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"time"

	"github.com/acme/shop/pkg/httpx"
	"gorm.io/gorm"
)

func baseURL() string {
	if v := os.Getenv("CUSTOMERS_SERVICE_URL"); v != "" {
		return v
	}
	return "http://customers-service:8080"
}

// remoteError is the error the in-process call returned, as customers-service
// answered it: the message in its JSON body ({"error": …}, or a problem's
// detail/title), unwrapped, so a caller shows exactly what the monolith showed.
// Use it for every answer of 400 or above, 404 included.
func remoteError(resp *http.Response) error {
	body, _ := io.ReadAll(io.LimitReader(resp.Body, 64<<10))
	var e struct {
		Error  string `json:"error"`
		Detail string `json:"detail"`
		Title  string `json:"title"`
	}
	if json.Unmarshal(body, &e) == nil {
		for _, m := range []string{e.Error, e.Detail, e.Title} {
			if m != "" {
				return errors.New(m)
			}
		}
	}
	return fmt.Errorf("customers-service: status %d", resp.StatusCode)
}

// Service is customers-service's Service, seen from orders: every method is a remote call.
type Service struct {
	baseURL string
	client  *http.Client
}

func newService() *Service {
	return &Service{baseURL: baseURL(), client: httpx.NewClient()}
}

const (
	maxAttempts = 3
	baseBackoff = 100 * time.Millisecond
)

// IsActive asks customers-service's POST /v1/customers/is_active. The call only
// reads, so transport errors and 5xx answers are retried with backoff.
func (c *Service) IsActive(id uint) (bool, error) {
	payload, err := json.Marshal(map[string]uint{"customerId": id})
	if err != nil {
		return false, err
	}
	var lastErr error
	for i := 0; i < maxAttempts; i++ {
		if i > 0 {
			time.Sleep(baseBackoff << (i - 1))
		}
		req, err := http.NewRequestWithContext(context.Background(), http.MethodPost, c.baseURL+"/v1/customers/is_active", bytes.NewReader(payload))
		if err != nil {
			return false, err
		}
		req.Header.Set("Content-Type", "application/json")
		resp, err := c.client.Do(req)
		if err != nil {
			lastErr = err
			continue
		}
		if resp.StatusCode >= 500 {
			lastErr = remoteError(resp)
			resp.Body.Close()
			continue
		}
		defer resp.Body.Close()
		if resp.StatusCode >= 400 {
			return false, remoteError(resp)
		}
		var out struct {
			Active bool `json:"active"`
		}
		if err := json.NewDecoder(resp.Body).Decode(&out); err != nil {
			return false, err
		}
		return out.Active, nil
	}
	return false, lastErr
}

func NewService(db *gorm.DB) *Service {
	return newService()
}
