// Code generated by port-monolith-go — the tables the service map assigned to payments.
package app

import (
	"github.com/acme/shop/services/payments/internal/payments"
)

// models lists the persisted types THIS service owns; New migrates exactly these.
func models() []any {
	return []any{
		&payments.Payment{},
	}
}
