// Code generated by port-monolith-go from cmd/shop/main.go — the monolith's own wiring,
// narrowed to the payments-service. An edit here is kept on the next port.
package app

import (
	"os"

	"github.com/acme/shop/services/payments/internal/payments"
	"github.com/acme/shop/services/payments/internal/platform"
	"github.com/gin-gonic/gin"
)

// wire constructs the payments-service's domain services and mounts its routes.
func wire(r *gin.Engine, d *Deps) error {
	db := d.DB
	paymentSvc := payments.NewService(db, payments.NewGateway(os.Getenv("PAYMENTS_URL")))
	r.Use(platform.AuthMiddleware())
	_ = paymentSvc
	return nil
}
