// Code generated by port-monolith-go from cmd/shop/main.go — the monolith's own wiring,
// narrowed to the payments-service. An edit here is kept on the next port.
package app

import (
	"os"

	"github.com/acme/shop/pkg/httpx"
	"github.com/acme/shop/services/payments/internal/payments"
	"github.com/acme/shop/services/payments/internal/platform"
	"github.com/gin-gonic/gin"
)

// wire constructs the payments-service's domain services and mounts its routes.
func wire(r *gin.Engine, d *Deps) error {
	db := d.DB
	paymentSvc := payments.NewService(db, payments.NewGateway(os.Getenv("PAYMENTS_URL")))
	auth := platform.AuthMiddleware()
	// A call from another service of this platform (pkg/httpx internal.go) skips the
	// monolith's user check, as the in-process call it replaces did.
	r.Use(func(c *gin.Context) {
		if httpx.IsInternal(c.Request) {
			c.Next()
			return
		}
		auth(c)
	})
	_ = paymentSvc
	return nil
}
